name: chop_shop_test
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  rxdart: ^0.27.7
  shared_preferences: ^2.1.0
  flutter_markdown: ^0.6.14
  url_launcher: ^6.1.10
  nima: ^1.0.5
  flare_flutter: ^3.0.2
  flare_dart: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/Articles/
#    - assets/Big_Bang/
    - assets/Milky Way/
    - assets/Mammals/
    - assets/Dinosaurs/
    - assets/Insects/
    - assets/Fish_and_Stuff/
    - assets/Cells/
    - assets/Dinosaur_Demise/
    - assets/Reptiles/
    - assets/World_War_I/
    - assets/Moon/
    - assets/Newton/
    - assets/Cold_war/
    - assets/Crusades/
    - assets/Homo_Sapiens_Sapiens/
    - assets/Nelson Mandela_v2/
    - assets/Martin Luther king/
    - assets/Sufraggette_movement/
    - assets/Marie_Curie/
    - assets/Amelia_Earhart/
    - assets/Alan_Turing/
    - assets/World_War_II/
    - assets/Darwin 2/
    - assets/Internet/
    - assets/Agricultural_evolution/
    - assets/Writing/
    - assets/Recorded_history/
    - assets/Pyramid/
    - assets/Roma/
    - assets/Industrialization/
    - assets/Constantinople/
    - assets/BlackPlague/
    - assets/First_Temple/
    - assets/Apes/
    - assets/Constructive_Tools/
    - assets/Fire/
    # - assets/search_icon.png
    # - assets/flutter_logo.png
    # - assets/right_arrow.png
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
flutter_intl:
  enabled: true
